# A workflow to run Bazel builds and tests.

name: precommit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'main'
      - 'beta'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build+test ${{ matrix.name }}

    runs-on: ${{ matrix.os }}

    timeout-minutes: 30

    strategy:
      fail-fast: ${{ github.event_name != 'workflow_dispatch' }}
      matrix:
        include:
          - { name: 'Linux GCC', os: 'ubuntu-22.04', cc: gcc-12, cxx: g++-12, config: ''}
          - { name: 'Linux LLVM+libstdc++', os: 'ubuntu-22.04', cc: clang, cxx: clang++, config: ''}
          - { name: 'Linux LLVM+libc++', os: 'ubuntu-22.04', cc: clang, cxx: clang++, config: --config=libc++ }
          - { name: 'MacOS LLVM+libc++', os: 'macos-12', cc: clang, cxx: clang++, config: --config=libc++ }
          - { name: 'M1 MacOS LLVM+libc++', os: 'macos-latest', cc: clang, cxx: clang++, config: --config=libc++ }

    env:
      CC:  ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v3
      - name: install infrastructure (Linux)
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get install python3-dev python3-numpy python3-packaging
          sudo ln -s /usr/lib/llvm-10/include/c++/v1 /usr/include/c++/v1
      - name: install infrastructure (MacOS)
        if: matrix.os == 'macos-12' || matrix.os == 'macos-latest'
        run: sudo -H pip3 install numpy packaging
      - name: build-and-test-lua5.1
        run: |
          bazel --bazelrc=.bazelrc build --config=lua5_1 ${{ matrix.config }} //...
          bazel --bazelrc=.bazelrc test  --config=lua5_1 ${{ matrix.config }} --test_output=errors //...
      - name: build-and-test-lua5.2
        run: |
          bazel --bazelrc=.bazelrc build --config=lua5_2 ${{ matrix.config }} //...
          bazel --bazelrc=.bazelrc test  --config=lua5_2 ${{ matrix.config }} --test_output=errors //...
      - name: build-and-test-luajit
        if: matrix.os == 'ubuntu-22.04'
        run: |
          bazel --bazelrc=.bazelrc build --config=luajit ${{ matrix.config }} //...
          bazel --bazelrc=.bazelrc test  --config=luajit ${{ matrix.config }} --test_output=errors //...
